import Navbar from "@/sections/Navbar";
import "./globals.css";
import Wrap from "@/sections/Wrap";

export const metadata = {
  title: "Playground - OpenAI API",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Wrap>
          <Navbar />
          {children}
        </Wrap>
      </body>
    </html>
  );
}
