import Navbar from "@/sections/Navbar";
import "./globals.css";
import Wrap from "@/sections/Wrap";
// import localFont from "next/font/local";
import MobileMenu from "@/sections/MobileMenu";

export const metadata = {
  title: "Playground - OpenAI API",
  description: "Generated by create next app"
};

// const colfax = localFont({
//   src: [
//     {
//       path: "../../public/assets/fonts/Colfax-Thin.otf",
//       weight: "200",
//       style: "normal"
//     },
//     {
//       path: "../../public/assets/fonts/Colfax-Light.otf",
//       weight: "300",
//       style: "normal"
//     },
//     {
//       path: "../../public/assets/fonts/Colfax-Regular.otf",
//       weight: "400",
//       style: "normal"
//     },
//     {
//       path: "../../public/assets/fonts/Colfax-Medium.otf",
//       weight: "500",
//       style: "normal"
//     },
//     {
//       path: "../../public/assets/fonts/Colfax-Bold.otf",
//       weight: "600",
//       style: "normal"
//     },
//     {
//       path: "../../public/assets/fonts/Colfax-Black.otf",
//       weight: "700",
//       style: "normal"
//     }
//   ]
// });

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Wrap>
          <Navbar />
          <MobileMenu />
          {children}
        </Wrap>
      </body>
    </html>
  );
}
